### PR TITLE
Add support for Enterprise Linux

### PR DESCRIPTION
**Pull request by timja**
`azavea.ruby` only worked on ubuntu.

I've changed it to use `rvm` which works a lot more widely.

### CODE REVIEW

**Comment by hectcastro** [comment]
Hey @timja-kainos, that for the PR.

We use `azavea.ruby` exclusively on Ubuntu, which is probably why it only worked there. That said, this particular role hasn't been used in our environment in a long while and is mostly deprecated. If you're interested in maintaining in, I'd be happy to transfer the ownership to you.

**Comment by timja** [comment]
Ok I would be happy to do that

**Comment by hectcastro** [comment]
Getting this error message from GitHub:

> timja-kainos/ansible-fpm already exists

**Comment by timja** [comment]
Try now

**Comment by hectcastro** [comment]
Had to move from the organization to myself in order to transfer direct to another user. Now getting:

> timja-kainos already has a repository in the hectcastro/ansible-fpm network

**Comment by timja** [comment]
I've deleted the forked repo.

**Comment by hectcastro** [comment]
screen shot 2016-12-14 at 17 16 40

**Pull request merged**
